// Level seed search: `node tools/check.js <world 1-5> [from-to]` (levels 1-20)
// For every level it tries seeds until the level
//   1. stands still on its own (nothing moves or breaks for 5 s), and
//   2. is won by a greedy bot that tries a grid of shots per bird, with no upgrades.
// Results go to tools/out/w<world>-<from>.json; `node tools/check.js merge` writes js/seeds.js.
const fs = require("fs");
const path = require("path");
const FF = require(path.join(__dirname, "../js/core.js"));
const WG = require(path.join(__dirname, "../js/worlds.js"));
const OUT = path.join(__dirname, "out");

function play(level, shots) {
  const g = new FF.Game(level);
  for (const s of shots) {
    if (g.state !== "ready") break;
    const a = s.angle * Math.PI / 180;
    g.launch(-Math.cos(a) * s.power * FF.MAX_PULL, -Math.sin(a) * s.power * FF.MAX_PULL);
    const t0 = g.time;
    let n = 0, tapped = false;
    while (g.state === "flying" && n++ < 2000) {
      if (s.tap != null && !tapped && g.time - t0 >= s.tap) { g.ability(); tapped = true; }
      g.step();
    }
    while (g.state === "bonus" && n++ < 4000) g.step();
  }
  return g;
}

function stability(level) {
  const g = new FF.Game(level);
  if (g.pigCount === 0) return "no pigs";
  const start = g.ents.filter(e => e.body && e.kind !== "rock").map(e => [e, e.body.getPosition().clone()]);
  for (let i = 0; i < 300; i++) g.step();
  let moved = 0;
  for (const [e, p] of start) {
    if (e.dead) return "something broke at rest";
    const q = e.body.getPosition();
    moved = Math.max(moved, Math.hypot(q.x - p.x, q.y - p.y));
  }
  if (g.score !== 0) return "damage at rest";
  if (moved > 0.06) return "moved " + moved.toFixed(2);
  return null;
}

function solve(level) {
  const shots = [];
  const angles = [];
  for (let a = -9; a <= 72; a += 3) angles.push(a);
  for (let turn = 0; turn < level.birds.length; turn++) {
    const type = level.birds[turn];
    const taps = { blue: [0.5, 0.85], yellow: [0.35, 0.65], white: [0.7, 1.0, 1.35] }[type] || [null];
    let best = null;
    for (const angle of angles) for (const power of [0.7, 0.85, 1.0]) for (const tap of taps) {
      const g = play(level, shots.concat([{ angle, power, tap }]));
      const val = (g.state === "won" || g.state === "bonus" ? 1e7 : 0) - g.pigCount * 1e5 + g.score;
      if (!best || val > best.val) best = { val, angle, power, tap, g };
    }
    shots.push({ angle: best.angle, power: best.power, tap: best.tap });
    if (best.g.state === "won") return { won: true, score: best.g.score, shots };
  }
  const g = play(level, shots);
  return { won: false, pigs: g.pigCount, score: g.score, shots };
}

if (process.argv[2] === "merge") {
  const all = [[], [], [], [], []];
  for (const f of fs.readdirSync(OUT)) {
    const d = JSON.parse(fs.readFileSync(path.join(OUT, f)));
    for (const [wi, li, rec] of d) all[wi][li] = rec;
  }
  const missing = [];
  all.forEach((w, wi) => { for (let li = 0; li < WG.PER_WORLD; li++) if (!w[li]) missing.push(`${wi + 1}-${li + 1}`); });
  if (missing.length) console.log("missing:", missing.join(" "));
  const body = all.map(w => "    [" + w.map(r => r ? JSON.stringify(r) : "null").join(", ") + "]").join(",\n");
  fs.writeFileSync(path.join(__dirname, "../js/seeds.js"),
`/* Generated by tools/check.js: per world, per level [seed, 2-star score, 3-star score]. */
(function (root) {
  const SEEDS = [
${body},
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = SEEDS;
  else root.FF_SEEDS = SEEDS;
})(typeof window !== "undefined" ? window : globalThis);
`);
  console.log("wrote js/seeds.js");
  process.exit(0);
}

const wi = Number(process.argv[2]) - 1;
const [from, to] = (process.argv[3] || "1-20").split("-").map(Number);
fs.mkdirSync(OUT, { recursive: true });
const res = [];
for (let li = from - 1; li < to; li++) {
  const t = Date.now();
  let done = false;
  for (let seed = 1; seed <= 25 && !done; seed++) {
    const lv = WG.generate(wi, li, seed);
    const st = stability(lv);
    if (st) { console.log(`${wi + 1}-${li + 1} seed ${seed}: unstable (${st})`); continue; }
    const s = solve(lv);
    if (!s.won) { console.log(`${wi + 1}-${li + 1} seed ${seed}: bot lost (${s.pigs} pigs left)`); continue; }
    const g = new FF.Game(lv);
    let [s2, s3] = g.stars();
    s3 = Math.round(Math.min(s3, s.score * 0.9) / 1000) * 1000;
    s2 = Math.round(Math.min(s2, s3 * 0.75) / 1000) * 1000;
    res.push([wi, li, [seed, s2, s3]]);
    console.log(`${wi + 1}-${li + 1} seed ${seed}: OK pigs ${g.pigCount} birds ${lv.birds.join(",")} bot ${s.score} with ${s.shots.length} | ${((Date.now() - t) / 1000) | 0}s`);
    done = true;
  }
  if (!done) console.log(`${wi + 1}-${li + 1}: NO SEED FOUND`);
  fs.writeFileSync(path.join(OUT, `w${wi + 1}-${from}.json`), JSON.stringify(res));
}
